# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2835548a03ec9cccbc3789d0c3bd726d76d3e190b38ad02b87e9eb9dbdbbaef0084468938b467b279f753f1df4c6f081d4cd020a631eb9f44e06312de4dad54d

test:
  secret_key_base: be655f113fc61451a035c984be05369b1d452235a0c3d77aaacf336ca3ac64d871ed6da74288a0a82f7dc61a94634a37e329eef7014f18a7b5f47a028e890fc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
